set_property PACKAGE_PIN B4 [get_ports {a_to_g[6]}]
set_property PACKAGE_PIN A4 [get_ports {a_to_g[5]}]
set_property PACKAGE_PIN A3 [get_ports {a_to_g[4]}]
set_property PACKAGE_PIN B1 [get_ports {a_to_g[3]}]
set_property PACKAGE_PIN A1 [get_ports {a_to_g[2]}]
set_property PACKAGE_PIN B3 [get_ports {a_to_g[1]}]
set_property PACKAGE_PIN B2 [get_ports {a_to_g[0]}]
set_property PACKAGE_PIN G2 [get_ports {led_bits[3]}]
set_property PACKAGE_PIN C2 [get_ports {led_bits[2]}]
set_property PACKAGE_PIN C1 [get_ports {led_bits[1]}]
set_property PACKAGE_PIN H1 [get_ports {led_bits[0]}]


set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN P15 [get_ports clr]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bits[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bits[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bits[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bits[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clr]


set_property IOSTANDARD LVCMOS33 [get_ports {pwdInput[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwdInput[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwdInput[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwdInput[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwdReg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwdReg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwdReg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwdReg[0]}]
set_property PACKAGE_PIN V4 [get_ports {pwdReg[3]}]
set_property PACKAGE_PIN R3 [get_ports {pwdReg[2]}]
set_property PACKAGE_PIN T3 [get_ports {pwdReg[1]}]
set_property PACKAGE_PIN T5 [get_ports {pwdReg[0]}]
set_property PACKAGE_PIN R2 [get_ports {pwdInput[3]}]
set_property PACKAGE_PIN M4 [get_ports {pwdInput[2]}]
set_property PACKAGE_PIN N4 [get_ports {pwdInput[1]}]
set_property PACKAGE_PIN R1 [get_ports {pwdInput[0]}]


set_property PACKAGE_PIN R15 [get_ports unlockKey]
set_property IOSTANDARD LVCMOS33 [get_ports unlockKey]




set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g2[0]}]
set_property PACKAGE_PIN D4 [get_ports {a_to_g2[6]}]
set_property PACKAGE_PIN E3 [get_ports {a_to_g2[5]}]
set_property PACKAGE_PIN D3 [get_ports {a_to_g2[4]}]
set_property PACKAGE_PIN F4 [get_ports {a_to_g2[3]}]
set_property PACKAGE_PIN F3 [get_ports {a_to_g2[2]}]
set_property PACKAGE_PIN E2 [get_ports {a_to_g2[1]}]
set_property PACKAGE_PIN D2 [get_ports {a_to_g2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bits2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bits2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bits2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bits2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwdInput[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwdInput[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwdInput[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwdInput[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwdReg[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwdReg[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwdReg[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwdReg[4]}]
set_property PACKAGE_PIN G1 [get_ports {led_bits2[3]}]
set_property PACKAGE_PIN F1 [get_ports {led_bits2[2]}]
set_property PACKAGE_PIN E1 [get_ports {led_bits2[1]}]
set_property PACKAGE_PIN G6 [get_ports {led_bits2[0]}]
set_property PACKAGE_PIN P5 [get_ports {pwdInput[7]}]
set_property PACKAGE_PIN P4 [get_ports {pwdInput[6]}]
set_property PACKAGE_PIN P3 [get_ports {pwdInput[5]}]
set_property PACKAGE_PIN P2 [get_ports {pwdInput[4]}]
set_property PACKAGE_PIN U3 [get_ports {pwdReg[7]}]
set_property PACKAGE_PIN U2 [get_ports {pwdReg[6]}]
set_property PACKAGE_PIN V2 [get_ports {pwdReg[5]}]
set_property PACKAGE_PIN V5 [get_ports {pwdReg[4]}]


set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN J2 [get_ports {led[1]}]
set_property PACKAGE_PIN K2 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports changeKey]
set_property PACKAGE_PIN R17 [get_ports changeKey]


set_property IOSTANDARD LVCMOS33 [get_ports resetKey]
set_property PACKAGE_PIN U4 [get_ports resetKey]
