set_property PACKAGE_PIN B4 [get_ports {a_to_g[6]}]
set_property PACKAGE_PIN A4 [get_ports {a_to_g[5]}]
set_property PACKAGE_PIN A3 [get_ports {a_to_g[4]}]
set_property PACKAGE_PIN B1 [get_ports {a_to_g[3]}]
set_property PACKAGE_PIN A1 [get_ports {a_to_g[2]}]
set_property PACKAGE_PIN B3 [get_ports {a_to_g[1]}]
set_property PACKAGE_PIN B2 [get_ports {a_to_g[0]}]
set_property PACKAGE_PIN G2 [get_ports {led_bits[3]}]
set_property PACKAGE_PIN C2 [get_ports {led_bits[2]}]
set_property PACKAGE_PIN C1 [get_ports {led_bits[1]}]
set_property PACKAGE_PIN H1 [get_ports {led_bits[0]}]


set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN P15 [get_ports clr]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a_to_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bits[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bits[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bits[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_bits[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clr]


set_property IOSTANDARD LVCMOS33 [get_ports {pwdInput[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwdInput[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwdInput[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwdInput[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwdReg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwdReg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwdReg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {pwdReg[0]}]
set_property PACKAGE_PIN V4 [get_ports {pwdReg[3]}]
set_property PACKAGE_PIN R3 [get_ports {pwdReg[2]}]
set_property PACKAGE_PIN T3 [get_ports {pwdReg[1]}]
set_property PACKAGE_PIN T5 [get_ports {pwdReg[0]}]
set_property PACKAGE_PIN R2 [get_ports {pwdInput[3]}]
set_property PACKAGE_PIN M4 [get_ports {pwdInput[2]}]
set_property PACKAGE_PIN N4 [get_ports {pwdInput[1]}]
set_property PACKAGE_PIN R1 [get_ports {pwdInput[0]}]


set_property PACKAGE_PIN R15 [get_ports unlockKey]
set_property IOSTANDARD LVCMOS33 [get_ports unlockKey]


